# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 22:31
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='edited_image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='share_code',
        ),
        migrations.AddField(
            model_name='photodetail',
            name='edited_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='photodetail',
            name='share_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
