# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20160716_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodetail',
            name='edited_image',
            field=models.TextField(default=''),
        ),
    ]
