# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20160716_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodetail',
            name='image_size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
