# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20160707_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='photos.Folder'),
        ),
        migrations.AddField(
            model_name='photodetail',
            name='effects',
            field=models.TextField(default=''),
        ),
    ]
