# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20160718_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='effects',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
