# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20160708_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='edited_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main'),
        ),
    ]
