# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20160713_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='share_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
